### ISSUE TITLE
RECREATE_VPN_CRON not working

### ISSUE THREAD

**Issue by acountrec** [azinchen/nordvpn#11]
Hi,
Not sure if you still update this, but the recreate does not work in a compose file? I haven't tested it in a docker run command but assume it not to be a difference.

here is my compose file
```
version: "3"
services:
  vpn:
    image: azinchen/nordvpn
    container_name: vpn
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
      # - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=user
      - PASS=password         # Required
      - RECREATE_VPN_CRON="*/5 * * * *"
      - RANDOM_TOP=1000
    restart: always

  autosel:
    build: .
    container_name: pypy
    command: python ./AutoSel.py
    network_mode: service:vpn
    depends_on:
      - vpn
    restart: always
    volumes:
      - C:/Users/acoun/PycharmProjects/PointsPrizes:/usr/src/app
```
