### ISSUE TITLE
nordvpn container with qbittorrent container

### ISSUE THREAD

**Issue by 96flose** [azinchen/nordvpn#12]
Hey there, I am having some problems with the linuxserver/qbittorrent docker container, maybe one of you might be able to help me. Here is my docker-compose.yml
```
version: "2"
services:
  vpn:
    image: azinchen/nordvpn:latest
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=notmy@email.com
      - PASS='notmypassword'
      - COUNTRY=Germany
      - CATEGORY=P2P
      - RANDOM_TOP=10
      - RECREATE_VPN_CRON=5 */6 * * *
      - NETWORK=192.168.0.0/24
      - OPENVPN_OPTS=--mute-replay-warnings
    ports:
      - 8080:80
      - 6881:6881
      - 6881:6881/udp
      - 8888:8888                 # Port on which the WEB-UI is hosted
    restart: unless-stopped

  web:                             # Still not 100% sure why I need that in here
    image: nginx
    network_mode: service:vpn
    
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:vpn      
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - UMASK_SET=022
      - WEBUI_PORT=8888
    volumes:
      - /home/pi/dockerconf/qbittorrent/config:/config
      - /home/pi/dockerconf/qbittorrent/downloads:/downloads
    restart: unless-stopped

#
# My Goal is to get qBittorrent running through the NordVPN container,
# so the traffic is encrypted. Right now I can open the WebUI, but my
# Ubuntu test torrent just doesn't start downloading. I've tried:
#    - Checking the qBittorrent settings to make sure the right port is selected
#    - going through the logs, but if you think they may help I'll send them
#

# it is only working while I am providing a proxy in the qBittorrent settings, but that defies
# the purpose of using a VPN at all. I would really appreciate any help I can get.
```
The full name of the qBittorrent container I am using is "linuxserver/qbittorrent.

Thank you in advance!

**Comment by azinchen** [comment]
First, docker-compose.yml should look something like this
```
version: "2"
services:
  vpn:
    image: azinchen/nordvpn:latest
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=notmy@email.com
      - PASS='notmypassword'
      - COUNTRY=Germany
      - CATEGORY=P2P
      - RANDOM_TOP=10
      - RECREATE_VPN_CRON=5 */6 * * *
      - NETWORK=192.168.0.0/24
      - OPENVPN_OPTS=--mute-replay-warnings
    ports:
      - 8888:8888                 # Port on which the WEB-UI is hosted
    restart: unless-stopped
    
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:vpn      
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - UMASK_SET=022
      - WEBUI_PORT=8888
    volumes:
      - /home/pi/dockerconf/qbittorrent/config:/config
      - /home/pi/dockerconf/qbittorrent/downloads:/downloads
    restart: unless-stopped
    depends_on:
      - vpn
```

But I got the same issue as yours, test torrent is always in Stalled mode.

Then I replaced qbittorrent with transmission, which I primary use in my environment.

```
version: '3'

services:
  vpn:
    image: azinchen/nordvpn:latest
    restart: unless-stopped
    ports:
      - 60605:9091/tcp
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - COUNTRY=Spain;Switzerland
      - CATEGORY=P2P
      - RANDOM_TOP=10
      - RECREATE_VPN_CRON=5 */3 * * *
      - NETWORK=192.168.1.0/24;192.168.2.0/24
      - USER=notmy@email.com
      - PASS='notmypassword'
      - OPENVPN_OPTS=--mute-replay-warnings
    volumes:
      - /etc/localtime:/etc/localtime:ro

  qbittorrent:
    image: linuxserver/transmission:latest
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
```
This test docker-compose file works Ok on my setup.

I think this is incompatibility issue of qbittorrent with NordVPN.
