### ISSUE TITLE
QBittorrent and NordVPN 

### ISSUE THREAD

**Issue by Zelatrix** [azinchen/nordvpn#13]
I hate to open an old issue, but I saw that issue #12 is closed, but has most of the information needed to get it working. However, I have looked into this and I still can't get it to work with my setup. The following is my Docker Compose file:
```
version: "3"
services:
   vpn:
     container_name: nordvpn
     image: azinchen/nordvpn:latest
     cap_add:
       - net_admin
     devices:
       - /dev/net/tun
     environment:
       - USER=xxxxxxxxxx
       - PASS=xxxxxxxxxx
       - CONNECT=United_Kingdom
       - CATEGORY=P2P
     ports:
       - 8080:8080
     restart: unless-stopped

   nginx:
     container_name: nginx
     image: dperson/nginx:latest
     links:
       - vpn:qbittorrent

   pihole:
     container_name: pihole
     image: pihole/pihole:latest
     ports:
       - "53:53/tcp"
       - "53:53/udp"
       - "8088:80/tcp"
       - "4433:443/tcp"
     restart: unless-stopped

   qbittorrent:
     container_name: qbittorrent
     image: linuxserver/qbittorrent:latest
     network_mode: service:vpn
     depends_on:
       - vpn
     environment:
       - WEBUI_PORT=8080
     restart: unless-stopped

   sonarr:
     container_name: sonarr
     image: linuxserver/sonarr:latest
     volumes:
       - "/media/pi/Seagate/Sonarr:/media/pi/storage"
       - "/config:/config"
     ports:
       - "8989:8989"
     restart: unless-stopped

   radarr:
     container_name: radarr
     image: linuxserver/radarr:latest
     volumes:
       - "/media/pi/Seagate/Radarr:/media/pi/storage"
       - "/config:/config-radarr"
     ports:
       - "7878:7878"
     restart: unless-stopped

   jackett:
     container_name: jackett
     image: linuxserver/jackett:latest
     ports:
       - "9117:9117"
     restart: unless-stopped
```
Is there something wrong with this file that prevents it from working?
