### ISSUE TITLE
How to connect to other container running on host?

### ISSUE THREAD

**Issue by realmallaury** [azinchen/nordvpn#20]
Hi, I have the following docker-compose: 
```version: "3"
services:
  vpn:
    container_name: vpn
    image: azinchen/nordvpn:latest
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=
      - PASS=
      - COUNTRY=United Kingdom;Norway;Spain;Switzerland
      - CATEGORY=Dedicated IP
      - RANDOM_TOP=20
      - RECREATE_VPN_CRON=*/30 * * * *
      - NETWORK=192.168.0.0/24
      - OPENVPN_OPTS=--mute-replay-warnings
      - PROTOCOL=openvpn_tcp
    restart: unless-stopped
  downloader:
    container_name: demo
    image: demo:0.0.1
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:pass@mysql:3306/demo
    restart: unless-stopped
    volumes:
    network_mode: service:vpn
```

I want to connect _demo_ container to outside _mysql_ container but I'm getting:
 `"Can't connect to MySQL server on 'mysql' ([Errno -2] Name or service not known)"`
Any suggestion on how I could go about it?
Thanks for putting together this great image.

**Comment by azinchen** [comment]
Not clear, do you want to connect from `demo` to `mysql` or from `mysql` to `demo`?

**Comment by realmallaury** [comment]
Sorry, it's from `demo` to `mysql`.

**Comment by azinchen** [comment]
Assuming that hostname of container with MySQL is `mysql`, you should add `mysql`'s subnet to `NETWORK` environment variable. `192.168.0.0/16;172.0.0.0/8` should cover all private subnets.

**Comment by realmallaury** [comment]
hm, I tried all of these: `- NETWORK=192.168.0.1/24;192.168.0.0/24;192.168.122.0/24;192.168.0.0/16;172.0.0.0/8` but im still geting the error

**Comment by azinchen** [comment]
How did you run `mysql` container?

**Comment by realmallaury** [comment]
In different compose file like this:
```
version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    ports:
      - 3308:3306
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: pass
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./:/docker-entrypoint-initdb.d
```
They are all running on same host.
