### ISSUE TITLE
Whitelist domain not working?

### ISSUE THREAD

**Issue by alpe12** [azinchen/nordvpn#98]
It gets added to iptables just fine.
`nordvpn-proxy     | Enabling connection to host br2.me`
But when I access the url (eg http://br2.me/images/v9XwEXYWpxt2rpkmFBiQ1zeyKUy_small.jpg), it keeps using the VPN for it instead of bypassing it. Resulting in an error 1005 because many of the BR nord servers are blacklisted by it.

```
  nordvpn-proxy:
    image: azinchen/nordvpn:latest
    container_name: nordvpn-proxy
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=myuser
      - PASS=mypass
      - COUNTRY=Brazil
      - GROUP=legacy_p2p
      - TECHNOLOGY=openvpn_udp
      - RANDOM_TOP=5
      - RECREATE_VPN_CRON=30 4 * * *
      - NETWORK=192.168.1.0/24
      - OPENVPN_OPTS=--mute-replay-warnings --auth-nocache --data-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC --pull-filter ignore "ping-restart" --ping-exit 180
      - CHECK_CONNECTION_CRON=*/15 * * * *
      - CHECK_CONNECTION_URL=https://www.google.com
      - WHITELIST=br2.me
    ports:
      - 8119:1080
    restart: unless-stopped

  nordvpn-socks5:
    image: serjs/go-socks5-proxy
    container_name: nordvpn-socks5
    depends_on:
      - nordvpn-proxy
    network_mode: "service:nordvpn-proxy"
```

Thanks.
